name: Stable

on:
  workflow_dispatch:
    inputs:
      branch:
        description: '?'
        required: true
        default: '狮鹫前线'
      windows:
        description: 'W'
        required: true
        type: boolean
        default: true
      ubuntu:
        description: 'L'
        required: true
        type: boolean
        default: true

jobs:
  build-windows:
    if: ${{ inputs.windows == true }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Campofinale-${{ inputs.branch }}-Windows
          path: Campofinale/bin/Release/net8.0

  build-ubuntu:
    if: ${{ inputs.ubuntu == true }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Campofinale-${{ inputs.branch }}-Linux
          path: Campofinale/bin/Release/net8.0
